import type { LucideIcon } from "lucide-react";
import {
  Apple,
  Bean,
  Beef,
  Bone,
  Candy,
  Cherry,
  CircleDot,
  Citrus,
  Coffee,
  CupSoda,
  Diamond,
  Droplets,
  Drumstick,
  Dumbbell,
  FlaskConical,
  FlaskRound,
  Flower2,
  Fuel,
  Milk,
  Palette,
  Sandwich,
  Shell,
  Sun,
  TestTube,
  TreeDeciduous,
  Waves,
  Wheat,
  Wind,
} from "lucide-react";
import type { IconName } from "@/lib/quiz/options";

export const OPTION_ICONS: Record<IconName, LucideIcon> = {
  droplets: Droplets,
  bean: Bean,
  candy: Candy,
  flask: FlaskConical,
  palette: Palette,
  "cup-soda": CupSoda,
  tree: TreeDeciduous,
  waves: Waves,
  "flask-round": FlaskRound,
  "test-tube": TestTube,
  fuel: Fuel,
  wheat: Wheat,
  bone: Bone,
  milk: Milk,
  beef: Beef,
  coffee: Coffee,
  apple: Apple,
  shell: Shell,
  sandwich: Sandwich,
  diamond: Diamond,
  flower: Flower2,
  "circle-dot": CircleDot,
  cherry: Cherry,
  wind: Wind,
  dumbbell: Dumbbell,
  drumstick: Drumstick,
  sun: Sun,
  citrus: Citrus,
};
